from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVaqtincha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_series', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KasallikTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('tugilgan_sana', models.DateField(verbose_name="Tug'ilgan sana")),
                ('millati', models.CharField(blank=True, max_length=100, verbose_name='Millati')),
                ('malumoti', models.CharField(blank=True, max_length=100, verbose_name="Ma'lumoti")),
                ('kasbi', models.CharField(blank=True, max_length=100, verbose_name='Kasbi')),
                ('ish_joyi', models.CharField(blank=True, max_length=255, verbose_name='Ish joyi')),
                ('ish_vazifasi', models.CharField(blank=True, max_length=255, verbose_name='Ish joyidagi vazifasi')),
                ('uy_manzili', models.CharField(blank=True, max_length=255, verbose_name='Uy manzili')),
                ('kelgan_vaqti', models.DateField(verbose_name='Kelgan vaqti')),
                ('shikoyatlar', models.TextField(blank=True, verbose_name='Kelgan vaqtdagi shikoyatlari')),
                ('asosiy_kasalliklar', models.TextField(blank=True, verbose_name='Asosiy tizimli kasalliklari')),
                ('asosiy_kasalliklar_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/asosiy_kasalliklar/')),
                ('nafas_tizimi', models.TextField(blank=True)),
                ('nafas_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/nafas_tizimi/')),
                ('yotal', models.TextField(blank=True, verbose_name="Yo'tal")),
                ('yotal_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/yotal/')),
                ('balgam', models.TextField(blank=True, verbose_name="Balg'am")),
                ('balgam_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/balgam/')),
                ('qon_tuflash', models.TextField(blank=True)),
                ('qon_tuflash_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/qon_tuflash/')),
                ('kokrak_ogriq', models.TextField(blank=True, verbose_name="Ko'krak qafasidagi og'riq")),
                ('kokrak_ogriq_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/kokrak_ogriq/')),
                ('nafas_qisishi', models.TextField(blank=True)),
                ('nafas_qisishi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/nafas_qisishi/')),
                ('yurak_qon_shikoyatlari', models.TextField(blank=True)),
                ('yurak_qon_shikoyatlari_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/yurak_qon_shikoyatlari/')),
                ('yurak_ogriq', models.TextField(blank=True)),
                ('yurak_ogriq_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/yurak_ogriq/')),
                ('yurak_urishi_ozgarishi', models.TextField(blank=True)),
                ('yurak_urishi_ozgarishi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/yurak_urishi_ozgarishi/')),
                ('yurak_urishi_sezish', models.TextField(blank=True)),
                ('yurak_urishi_sezish_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/yurak_urishi_sezish/')),
                ('hazm_tizimi', models.TextField(blank=True)),
                ('hazm_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/hazm_tizimi/')),
                ('qusish', models.TextField(blank=True)),
                ('qusish_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/qusish/')),
                ('qorin_ogriq', models.TextField(blank=True)),
                ('qorin_ogriq_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/qorin_ogriq/')),
                ('qorin_shish', models.TextField(blank=True)),
                ('qorin_shish_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/qorin_shish/')),
                ('ich_ozgarishi', models.TextField(blank=True)),
                ('ich_ozgarishi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/ich_ozgarishi/')),
                ('anus_shikoyatlar', models.TextField(blank=True)),
                ('anus_shikoyatlar_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/anus_shikoyatlar/')),
                ('siydik_tizimi', models.TextField(blank=True, verbose_name='Siydik ajratish tizimi faoliyati')),
                ('siydik_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/siydik_tizimi/')),
                ('endokrin_tizimi', models.TextField(blank=True)),
                ('endokrin_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/endokrin_tizimi/')),
                ('tayanch_tizimi', models.TextField(blank=True)),
                ('tayanch_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/tayanch_tizimi/')),
                ('asab_tizimi', models.TextField(blank=True)),
                ('asab_tizimi_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/asab_tizimi/')),
                ('doktor_tavsiyalari', models.TextField(blank=True)),
                ('doktor_tavsiyalari_hujjat', models.FileField(blank=True, null=True, upload_to='kasallik_hujjatlari/doktor_tavsiyalari/')),
                ('yuborilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='kasalliklar', to='patients.patientvaqtincha')),
            ],
        ),
    ]


