# Generated by Django 5.2.5 on 2025-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientvaqtincha_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvaqtincha',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvaqtincha',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvaqtincha',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('archived', 'Архивный'), ('deleted', 'Удаленный')], default='active', max_length=10),
        ),
    ]
