# Generated by Django 5.2.5 on 2025-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientvaqtincha_archived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvaqtincha',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='patientvaqtincha',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='patientvaqtincha',
            name='status',
        ),
    ]
