# Generated by Django 5.2.5 on 2025-09-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientvaqtincha_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to='patients.patientvaqtincha'),
        ),
    ]
