# Generated by Django 5.2.8 on 2025-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvaqtincha',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A(II) Rh+'), ('A-', 'A(II) Rh-'), ('B+', 'B(III) Rh+'), ('B-', 'B(III) Rh-'), ('AB+', 'AB(IV) Rh+'), ('AB-', 'AB(IV) Rh-'), ('O+', 'O(I) Rh+'), ('O-', 'O(I) Rh-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientvaqtincha',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True),
        ),
    ]
