# Generated by Django 6.0 on 2025-12-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patientvaqtincha_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasalliktarixi',
            name='ai_tahlil',
            field=models.TextField(blank=True, verbose_name='AI tahlili va tashxisi'),
        ),
    ]
