# Generated by Django 6.0 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_kasalliktarixi_ai_tahlil'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasalliktarixi',
            name='allergiyalar',
            field=models.TextField(blank=True, verbose_name='Allergiyalar'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='bosh_boyin',
            field=models.TextField(blank=True, verbose_name="Bosh va bo'yin"),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='limfa_tugunlari',
            field=models.TextField(blank=True, verbose_name='Limfa tugunlari'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='oilaviy_anamnez',
            field=models.TextField(blank=True, verbose_name='Oilaviy anamnez'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='opka_auskultatsiyasi',
            field=models.TextField(blank=True, verbose_name="O'pka auskultatsiyasi"),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='otkazilgan_kasalliklar',
            field=models.TextField(blank=True, verbose_name="O'tkazilgan kasalliklar"),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='perkussiya',
            field=models.TextField(blank=True, verbose_name='Perkussiya'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='qorin_auskultatsiyasi',
            field=models.TextField(blank=True, verbose_name='Qorin auskultatsiyasi'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='qorin_palpatsiyasi',
            field=models.TextField(blank=True, verbose_name='Qorin palpatsiyasi'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='teri',
            field=models.TextField(blank=True, verbose_name='Teri holati'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='umumiy_korik',
            field=models.TextField(blank=True, verbose_name="Umumiy ko'rik"),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='yurak_auskultatsiyasi',
            field=models.TextField(blank=True, verbose_name='Yurak auskultatsiyasi'),
        ),
        migrations.AddField(
            model_name='kasalliktarixi',
            name='zararli_odatlar',
            field=models.TextField(blank=True, verbose_name='Zararli odatlar'),
        ),
    ]
