# Generated by Django 5.2.3 on 2025-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('internal_medicine', 'Терапия (внутренние болезни)'), ('cardiology', 'Кардиология'), ('endocrinology', 'Эндокринология'), ('pulmonology', 'Пульмонология'), ('gastroenterology', 'Гастроэнтерология'), ('nephrology', 'Нефрология'), ('hematology', 'Гематология'), ('rheumatology', 'Ревматология'), ('allergy_immunology', 'Аллергология и иммунология'), ('infectious_diseases', 'Инфекционные болезни'), ('general_surgery', 'Общая хирургия'), ('cardiovascular_surgery', 'Сердечно-сосудистая хирургия'), ('neurosurgery', 'Нейрохирургия'), ('orthopedics_traumatology', 'Ортопедия и травматология'), ('urology', 'Урология'), ('plastic_surgery', 'Пластическая хирургия'), ('pediatric_surgery', 'Детская хирургия'), ('oncological_surgery', 'Онкохирургия'), ('thoracic_surgery', 'Торакальная хирургия'), ('maxillofacial_surgery', 'Челюстно-лицевая хирургия'), ('obstetrics_gynecology', 'Акушерство и гинекология'), ('pediatrics', 'Педиатрия'), ('neurology', 'Неврология'), ('psychiatry', 'Психиатрия'), ('dermatovenereology', 'Дерматовенерология'), ('ophthalmology', 'Офтальмология'), ('otolaryngology', 'Отоларингология (ЛОР)'), ('dentistry', 'Стоматология'), ('radiology', 'Радиология'), ('ultrasound_diagnostics', 'Ультразвуковая диагностика'), ('laboratory_diagnostics', 'Лабораторная диагностика'), ('pathomorphology', 'Патоморфология (патанатомия)'), ('functional_diagnostics', 'Функциональная диагностика'), ('medical_genetics', 'Медицинская генетика'), ('medical_rehabilitation', 'Медицинская реабилитация'), ('geriatrics', 'Гериатрия'), ('palliative_care', 'Паллиативная медицина'), ('sports_medicine', 'Спортивная медицина'), ('clinical_oncology', 'Клиническая онкология'), ('medical_cybernetics_ai', 'Медицинская кибернетика и ИИ в медицине'), ('transplantology', 'Трансплантология'), ('reproductive_medicine', 'Репродуктивная медицина')], max_length=50),
        ),
    ]
