# Generated by Django 5.2.3 on 2025-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_hospital_doctor_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography or professional statement for the profile page.', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text="A list of more specific specializations, e.g., ['Echocardiography', 'Interventional Cardiology']"),
        ),
    ]
